services:
  mongo:
    image: mongo:7
    container_name: mongo
    ports:
      - "27018:27017"
    volumes:
      - mongo_data:/data/db

  patient-service:
    build: ./backend/patient-service
    environment:
      - PORT=4001
      - MONGO_URI=mongodb://mongo:27017/healthcare_core
      - CORS_ORIGIN=http://localhost:5173
    depends_on:
      - mongo
    ports:
      - "4001:4001"

  appointment-service:
    build: ./backend/appointment-service
    environment:
      - PORT=4002
      - MONGO_URI=mongodb://mongo:27017/healthcare_core
      - CORS_ORIGIN=http://localhost:5173
    depends_on:
      - mongo
    ports:
      - "4002:4002"

  api-gateway:
    build: ./backend/api-gateway
    environment:
      - PORT=4000
      - CORS_ORIGIN=http://localhost:5173
      - PATIENT_SERVICE_URL=http://patient-service:4001
      - APPOINTMENT_SERVICE_URL=http://appointment-service:4002
    depends_on:
      - patient-service
      - appointment-service
    ports:
      - "4000:4000"

  frontend:
    build: ./frontend
    environment:
      - VITE_API_BASE_URL=http://localhost:4000
    depends_on:
      - api-gateway
    ports:
      - "5173:5173"

volumes:
  mongo_data:
